INSERT INTO "APP"."OPERADOR" ("ID", "TIPO", "URL") VALUES ('1', 'NORMAL', 'url1')
INSERT INTO "APP"."OPERADOR" ("ID", "TIPO", "URL") VALUES ('2', 'NORMAL', 'url2')
INSERT INTO "APP"."OPERADOR" ("ID", "TIPO", "URL") VALUES ('3', 'PREMIUM', 'url3')